stages:
  - review

prev_review:
  stage: review
  image: golang:1.24
  rules:
    - if: $CI_MERGE_REQUEST_IID
      when: on_success
    - when: never
  script:
    - mkdir -p "$HOME/.config/prev"
    - cp examples/configs/v1-gitlab-ci-review.yml "$HOME/.config/prev/config.yml"
    - go install github.com/sanix-darker/prev@latest
    - prev config validate
    - prev mr review "$CI_PROJECT_PATH" "$CI_MERGE_REQUEST_IID" --strictness strict
  variables:
    PREV_PROVIDER: "openai"
    OPENAI_API_MODEL: "gpt-5.2-chat-latest"

